blank_issues_enabled: false
contact_links:
  - name: Contact Us
    url: https://bloodontheclocktower.com/pages/contact-us
    about: If you want to get in touch with us through other means
  - name: Online Store
    url: https://bloodontheclocktower.com/products/blood-on-the-clocktower-the-game
    about: If you want to buy the physical game
