blank_issues_enabled: false
contact_links:
  - name: Online Store
    url: https://bloodontheclocktower.com/products/blood-on-the-clocktower-the-game
    about: If you want to buy the physical game
  - name: Blood on the Clocktower Terms & Policies
    url: https://bloodontheclocktower.com/pages/blood-on-the-clocktower-online-policy-terms-of-use
    about: If you want to know more about the terms of use for the official app
